spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\SEC.EDUCACAO\Documents\ecom-application\configserver\src\main\resources\config

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
    port: 8888
